### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by WN1695173791** [jiamings/d2c#1]
Do you have a training process for this model？

**Comment by WN1695173791** [comment]
How did you get your checkpoint?

**Comment by WN1695173791** [comment]
from runners.diffusion import Diffusion
https://github.com/jiamings/d2c/blob/65b22628900fe1e37848308511c064933ad2ab0b/d2c/diffusion/main.py#L12


I didn't find the runner file in your code

**Comment by WN1695173791** [comment]
Hope to get your reply, thank you

**Comment by WN1695173791** [comment]
https://github.com/ermongroup/ddim/blob/34d640e5180cc5ab378f84af6ed596cb0c810e6c/runners/diffusion.py#L61



Is this the file

**Comment by jiamings** [comment]
See #2 .
