### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by WN1695173791** [jiamings/d2c#2]
Can the author explain the training process clearly in readme？

**Comment by WN1695173791** [comment]
"We will release training code soon on a separate repo, as the GPU memory becomes a bottleneck if we train the model jointly."

Can you release the training code as soon as possible？

**Comment by jiamings** [comment]
We will release the training code but not right now. We have other commitments at the moment, so please be patient while we clean up the code.

**Comment by WN1695173791** [comment]
Thank you very much.

**Comment by SnowdenLee** [comment]
Hello, 
may I ask do you have an estimated publication time? 
Thanks a lot.

**Comment by WN1695173791** [comment]
I was gonna ask you the same question. @jiamings
