### ISSUE TITLE
Is Red_Lipstick is the same class as Wearing_Lipstick in the original attribute annotation format of CelebA?

### ISSUE THREAD

**Issue by nessessence** [jiamings/d2c#3]
Hi, 
I wonder if Red_Lipstick is the same attribute as Wearing_Lipstick in the original attribute annotation format of CelebA here?
https://drive.google.com/drive/folders/0B7EVK8r0v71pOC0wOVZlQnFfaGs?resourcekey=0-pEjrQoTrlbjZJO2UL8K_WQ
if not, how did you get that annotation? 

Thank you for sharing an interesting work to the community.

**Comment by jiamings** [comment]
@a7b23 might be able to answer this question.

**Comment by a7b23** [comment]
Hi, 
We had manually curated this small dataset from CelebA. Since we required only 50 images so it was easily doable.
